# Generated by Django 5.1.4 on 2024-12-18 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('rating_inicial', models.DecimalField(decimal_places=2, max_digits=5)),
                ('club', models.CharField(blank=True, max_length=255, null=True)),
                ('createdU', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('modifiedU', models.DateTimeField(auto_now=True, verbose_name='Modificado')),
            ],
        ),
    ]
