# Generated by Django 5.1.4 on 2025-01-03 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_alter_usuario_rating_inicial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rating_inicial',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
