# Generated by Django 5.1.4 on 2024-12-18 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Partido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipo_1', models.CharField(max_length=255)),
                ('equipo_2', models.CharField(max_length=255)),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('resultado', models.CharField(blank=True, max_length=255, null=True)),
                ('createdP', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('modifiedP', models.DateTimeField(auto_now=True, verbose_name='Modificado')),
            ],
        ),
    ]
