# Generated by Django 5.1.4 on 2025-02-11 18:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('torneos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Partido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('resultado', models.CharField(blank=True, max_length=255, null=True)),
                ('createdP', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('modifiedP', models.DateTimeField(auto_now=True, verbose_name='Modificado')),
                ('equipo_1', models.ManyToManyField(related_name='equipo_1', to=settings.AUTH_USER_MODEL, verbose_name='Equipo 1')),
                ('equipo_2', models.ManyToManyField(related_name='equipo_2', to=settings.AUTH_USER_MODEL, verbose_name='Equipo 2')),
                ('torneo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partidos', to='torneos.torneo', verbose_name='Torneo')),
            ],
        ),
    ]
