# Generated by Django 5.1.4 on 2025-01-06 03:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partidos', '0001_initial'),
        ('torneos', '0004_remove_torneo_tags_delete_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='partido',
            name='torneo',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='partidos', to='torneos.torneo', verbose_name='Torneo'),
            preserve_default=False,
        ),
    ]
