# Generated by Django 5.1.4 on 2025-01-09 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partidos', '0002_partido_torneo'),
        ('usuarios', '0003_alter_usuario_rating_inicial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partido',
            name='equipo_1',
        ),
        migrations.RemoveField(
            model_name='partido',
            name='equipo_2',
        ),
        migrations.AddField(
            model_name='partido',
            name='equipo_1',
            field=models.ManyToManyField(limit_choices_to=2, related_name='equipo_1', to='usuarios.usuario', verbose_name='Equipo 1'),
        ),
        migrations.AddField(
            model_name='partido',
            name='equipo_2',
            field=models.ManyToManyField(limit_choices_to=2, related_name='equipo_2', to='usuarios.usuario', verbose_name='Equipo 2'),
        ),
    ]
