# Generated by Django 5.1.4 on 2025-01-10 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partidos', '0003_remove_partido_equipo_1_remove_partido_equipo_2_and_more'),
        ('usuarios', '0003_alter_usuario_rating_inicial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partido',
            name='equipo_1',
            field=models.ManyToManyField(related_name='equipo_1', to='usuarios.usuario', verbose_name='Equipo 1'),
        ),
        migrations.AlterField(
            model_name='partido',
            name='equipo_2',
            field=models.ManyToManyField(related_name='equipo_2', to='usuarios.usuario', verbose_name='Equipo 2'),
        ),
    ]
