# Generated by Django 5.1.4 on 2024-12-18 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Torneo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('sede', models.CharField(max_length=255)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('premio_dinero', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Premio ($)')),
                ('createdT', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('modifiedT', models.DateTimeField(auto_now=True, verbose_name='Modificado')),
            ],
        ),
    ]
