# Generated by Django 5.1.4 on 2025-01-03 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torneos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='torneo',
            name='imagen_url',
            field=models.URLField(default=0, max_length=500, verbose_name='Imagen URL'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='torneo',
            name='puntos',
            field=models.IntegerField(default=0, verbose_name='Puntos para Ranking'),
        ),
        migrations.AddField(
            model_name='torneo',
            name='tags',
            field=models.ManyToManyField(blank=True, to='torneos.tag', verbose_name='Categorías del Torneo'),
        ),
    ]
