# Generated by Django 5.1.4 on 2025-01-03 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torneos', '0002_tag_torneo_imagen_url_torneo_puntos_torneo_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='nombre',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='torneo',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, to='torneos.tag', verbose_name='Categorías del Torneo'),
        ),
    ]
