# Generated by Django 5.1.4 on 2025-01-04 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('torneos', '0003_alter_tag_nombre_alter_torneo_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='torneo',
            name='tags',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
