# Generated by Django 5.1.4 on 2025-02-10 20:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActividadReciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('tipo', models.CharField(choices=[('usuario', 'Usuario'), ('partido', 'Partido'), ('torneo', 'Torneo')], max_length=10)),
                ('descripcion', models.TextField()),
                ('estado', models.CharField(blank=True, choices=[('pending', 'Pendiente'), ('approved', 'Aprobado'), ('rejected', 'Rechazado'), ('directo', 'Directo')], default='', max_length=10)),
                ('aprobacion_id', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
