# Generated by Django 5.1.4 on 2025-01-22 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividad', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividadreciente',
            name='aprobacion_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
