# Generated by Django 5.1.4 on 2025-01-24 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividad', '0002_actividadreciente_aprobacion_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividadreciente',
            name='estado',
            field=models.CharField(blank=True, choices=[('pending', 'Pendiente'), ('approved', 'Aprobado'), ('rejected', 'Rechazado'), ('directo', 'Directo')], default='', max_length=10),
        ),
    ]
